/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.courier.ui;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 *
 * @author kabin
 */
public class ContactsFrame extends JFrame {
    private JTextField fullNameField;
    private JTextField mobileNumberField;
    private JTextField emailField;
    private JTextArea messageArea;
    private JButton contactUsButton;

    /**
     * Creates new form java
     */
    public ContactsFrame() {
        setTitle("nepXpress — Contact");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(1280, 720);
        setLocationRelativeTo(null);
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }// </editor-fold>//GEN-END:initComponents

    private void setupUI() {
        // Main container with padding
        JPanel mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBackground(Color.WHITE);

        // Header panel with title
        JPanel headerPanel = new JPanel();
        headerPanel.setLayout(new BoxLayout(headerPanel, BoxLayout.Y_AXIS));
        headerPanel.setBackground(Color.WHITE);
        headerPanel.setBorder(new EmptyBorder(16, 25, 16, 25));

        JLabel contactsTitle = new JLabel("Contact");
        contactsTitle.setFont(new Font("SansSerif", Font.BOLD, 24));
        contactsTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        headerPanel.add(contactsTitle);
        
        JSeparator separator = new JSeparator();
        separator.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
        separator.setForeground(new Color(200, 200, 200));
        headerPanel.add(Box.createVerticalStrut(8));
        headerPanel.add(separator);

        mainPanel.add(headerPanel, BorderLayout.NORTH);

        // Content Panel with Contact Info and Form side by side
        JPanel contentPanel = new JPanel(new GridLayout(1, 2, 30, 0));
        contentPanel.setBackground(Color.WHITE);
        contentPanel.setBorder(new EmptyBorder(20, 25, 20, 25));

        // Left side - Contact Information
        JPanel contactInfoPanel = new JPanel();
        contactInfoPanel.setLayout(new BoxLayout(contactInfoPanel, BoxLayout.Y_AXIS));
        contactInfoPanel.setBackground(Color.WHITE);

        // Contact Information Title
        JLabel contactInfoTitle = new JLabel("Contact Information");
        contactInfoTitle.setFont(new Font("SansSerif", Font.BOLD, 20));
        contactInfoTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(contactInfoTitle);
        contactInfoPanel.add(Box.createVerticalStrut(20));

        // Address Section
        JLabel addressTitle = new JLabel("Address");
        addressTitle.setFont(new Font("SansSerif", Font.BOLD, 16));
        addressTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(addressTitle);

        JLabel addressLine1 = new JLabel("Sundarbasti, Budhanilkantha-8");
        JLabel addressLine2 = new JLabel("Kathmandu, Nepal");
        addressLine1.setForeground(Color.GRAY);
        addressLine2.setForeground(Color.GRAY);
        addressLine1.setAlignmentX(Component.LEFT_ALIGNMENT);
        addressLine2.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(addressLine1);
        contactInfoPanel.add(addressLine2);
        contactInfoPanel.add(Box.createVerticalStrut(20));

        // Phone Section
        JLabel phoneTitle = new JLabel("Phone No");
        phoneTitle.setFont(new Font("SansSerif", Font.BOLD, 16));
        phoneTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(phoneTitle);

        JLabel phone1 = new JLabel("9708059955");
        JLabel phone2 = new JLabel("9814830254");
        phone1.setForeground(Color.GRAY);
        phone2.setForeground(Color.GRAY);
        phone1.setAlignmentX(Component.LEFT_ALIGNMENT);
        phone2.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(phone1);
        contactInfoPanel.add(phone2);
        contactInfoPanel.add(Box.createVerticalStrut(20));

        // Email Section
        JLabel emailTitle = new JLabel("Email");
        emailTitle.setFont(new Font("SansSerif", Font.BOLD, 16));
        emailTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(emailTitle);

        JLabel emailLabel = new JLabel("nepXpresscourier@gmail.com");
        emailLabel.setForeground(Color.GRAY);
        emailLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactInfoPanel.add(emailLabel);

        // Right side - Contact Form
        JPanel contactFormPanel = new JPanel();
        contactFormPanel.setLayout(new BoxLayout(contactFormPanel, BoxLayout.Y_AXIS));
        contactFormPanel.setBackground(Color.WHITE);

        // Contact Form Title
        JLabel formTitle = new JLabel("Contact Form");
        formTitle.setFont(new Font("SansSerif", Font.BOLD, 20));
        formTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
        contactFormPanel.add(formTitle);
        contactFormPanel.add(Box.createVerticalStrut(20));

        // Form Fields
        fullNameField = createFormField("Full Name*");
        mobileNumberField = createFormField("Mobile Number*");
        emailField = createFormField("Email*");
        
        // Message Area
        messageArea = new JTextArea();
        messageArea.setFont(new Font("SansSerif", Font.PLAIN, 14));
        messageArea.setLineWrap(true);
        messageArea.setWrapStyleWord(true);
        messageArea.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        messageArea.setText("Message*");
        messageArea.setForeground(Color.GRAY);
        JScrollPane scrollPane = new JScrollPane(messageArea);
        scrollPane.setMaximumSize(new Dimension(Integer.MAX_VALUE, 150));
        
        // Character limit label
        JLabel charLimit = new JLabel("maximum 250 characters");
        charLimit.setFont(new Font("SansSerif", Font.ITALIC, 12));
        charLimit.setForeground(Color.GRAY);
        charLimit.setAlignmentX(Component.RIGHT_ALIGNMENT);

        // Contact Us Button
        contactUsButton = new JButton("Contact us");
        contactUsButton.setBackground(new Color(242, 140, 72)); // Orange color
        contactUsButton.setForeground(Color.WHITE);
        contactUsButton.setFont(new Font("SansSerif", Font.BOLD, 14));
        contactUsButton.setMaximumSize(new Dimension(120, 40));
        contactUsButton.setBorderPainted(false);
        contactUsButton.setFocusPainted(false);

        // Add components to form panel
        contactFormPanel.add(fullNameField);
        contactFormPanel.add(Box.createVerticalStrut(15));
        contactFormPanel.add(mobileNumberField);
        contactFormPanel.add(Box.createVerticalStrut(15));
        contactFormPanel.add(emailField);
        contactFormPanel.add(Box.createVerticalStrut(15));
        contactFormPanel.add(scrollPane);
        contactFormPanel.add(Box.createVerticalStrut(5));
        contactFormPanel.add(charLimit);
        contactFormPanel.add(Box.createVerticalStrut(20));
        contactFormPanel.add(contactUsButton);

        // Add panels to content panel
        contentPanel.add(contactInfoPanel);
        contentPanel.add(contactFormPanel);

        mainPanel.add(contentPanel, BorderLayout.CENTER);
        setContentPane(mainPanel);

        // Add action listener for contact button
        contactUsButton.addActionListener(e -> handleContactSubmit());
    }

    private JTextField createFormField(String placeholder) {
        JTextField field = new JTextField(placeholder);
        field.setFont(new Font("SansSerif", Font.PLAIN, 14));
        field.setForeground(Color.GRAY);
        field.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        field.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(Color.GRAY);
                }
            }
        });

        return field;
    }

    private void handleContactSubmit() {
        String fullName = fullNameField.getText().trim();
        String mobileNumber = mobileNumberField.getText().trim();
        String email = emailField.getText().trim();
        String message = messageArea.getText().trim();

        // Validate input
        if (fullName.isEmpty() || fullName.equals("Full Name*") ||
            mobileNumber.isEmpty() || mobileNumber.equals("Mobile Number*") ||
            email.isEmpty() || email.equals("Email*") ||
            message.isEmpty() || message.equals("Message*")) {
            
            JOptionPane.showMessageDialog(this,
                "Please fill in all required fields",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate email format
        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email address",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate mobile number format
        if (!mobileNumber.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid 10-digit mobile number",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate message length
        if (message.length() > 250) {
            JOptionPane.showMessageDialog(this,
                "Message cannot exceed 250 characters",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // TODO: Send message to server
        JOptionPane.showMessageDialog(this,
            "Thank you for your message. We will get back to you soon!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
        clearForm();
    }

    private void clearForm() {
        fullNameField.setText("Full Name*");
        fullNameField.setForeground(Color.GRAY);
        mobileNumberField.setText("Mobile Number*");
        mobileNumberField.setForeground(Color.GRAY);
        emailField.setText("Email*");
        emailField.setForeground(Color.GRAY);
        messageArea.setText("Message*");
        messageArea.setForeground(Color.GRAY);
    }

    public JPanel getMainPanel() {
        return (JPanel) getContentPane();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        EventQueue.invokeLater(() -> {
            new ContactsFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
